// <auto-generated />
using System;
using AppDevicesMedical.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppDevicesMedical.Migrations
{
    [DbContext(typeof(MedicalDevicesDbContext))]
    [Migration("20251104204136_Dispositivos")]
    partial class Dispositivos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppDevicesMedical.Models.Auditoria", b =>
                {
                    b.Property<int>("Id_log")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_log"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Detalles")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Id_usuario")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Ip_address")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id_log");

                    b.ToTable("Auditoria");
                });

            modelBuilder.Entity("AppDevicesMedical.Models.Categoria", b =>
                {
                    b.Property<int>("Id_Categoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Categoria"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Fecha_de_creación")
                        .HasColumnType("Date");

                    b.Property<string>("Nombre_Categoria")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id_Categoria");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("AppDevicesMedical.Models.ClaseRiesgo", b =>
                {
                    b.Property<int>("Id_clase_riesgo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_clase_riesgo"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre_clase")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id_clase_riesgo");

                    b.ToTable("ClaseRiesgo");
                });

            modelBuilder.Entity("AppDevicesMedical.Models.Cuarto", b =>
                {
                    b.Property<int>("Id_cuarto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_cuarto"));

                    b.Property<int?>("Capacidad_hvac_cfm")
                        .HasColumnType("int");

                    b.Property<int>("Capacidad_personas")
                        .HasColumnType("int");

                    b.Property<string>("Clase_cuarto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Control_humedad")
                        .HasColumnType("bit");

                    b.Property<bool>("Control_temperatura")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Dimensiones_m2")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Equipamiento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Espec_flujo_aire")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Estado_inspeccion_listo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("Fecha_ultima_validacion")
                        .HasColumnType("Date");

                    b.Property<string>("Notas_adicionales")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Periodo_revalidacion_meses")
                        .HasColumnType("int");

                    b.Property<string>("Protocolo_acceso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Protocolo_validacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Tiempo_reposicion_aire_min")
                        .HasColumnType("int");

                    b.Property<string>("Tipo_acondicionamiento")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id_cuarto");

                    b.ToTable("Cuarto");
                });

            modelBuilder.Entity("AppDevicesMedical.Models.Dispositivo", b =>
                {
                    b.Property<string>("Id_dispositivo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descripcion_detallada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Es_invasivo")
                        .HasColumnType("bit");

                    b.Property<string>("Estado_regulatorio")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Fecha_registro")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Id_categoria")
                        .HasColumnType("int");

                    b.Property<int?>("Id_clase_riesgo")
                        .HasColumnType("int");

                    b.Property<int?>("Id_cuarto_requerido")
                        .HasColumnType("int");

                    b.Property<int?>("Id_tipo_dispositivo")
                        .HasColumnType("int");

                    b.Property<string>("Metodo_esterilizacion_req")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("Requiere_biocompatibilidad")
                        .HasColumnType("bit");

                    b.Property<bool>("Requiere_prueba_residuales")
                        .HasColumnType("bit");

                    b.HasKey("Id_dispositivo");

                    b.HasIndex("Id_categoria");

                    b.HasIndex("Id_clase_riesgo");

                    b.HasIndex("Id_cuarto_requerido");

                    b.HasIndex("Id_tipo_dispositivo");

                    b.ToTable("Dispositivos");
                });

            modelBuilder.Entity("AppDevicesMedical.Models.Especialidad", b =>
                {
                    b.Property<int>("Id_Especialidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Especialidad"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom_Especialidad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id_Especialidad");

                    b.ToTable("Especialidad");
                });

            modelBuilder.Entity("AppDevicesMedical.Models.Examen", b =>
                {
                    b.Property<int>("IdExamen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdExamen"));

                    b.Property<string>("EnlaceFormulario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IdExamen");

                    b.ToTable("Examenes");
                });

            modelBuilder.Entity("AppDevicesMedical.Models.Normas", b =>
                {
                    b.Property<int>("Id_norma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_norma"));

                    b.Property<string>("Codigo_norma")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id_norma");

                    b.ToTable("Normas");
                });

            modelBuilder.Entity("AppDevicesMedical.Models.Rol", b =>
                {
                    b.Property<int>("Id_rol")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre_rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id_rol");

                    b.ToTable("Rol");

                    b.HasData(
                        new
                        {
                            Id_rol = 1,
                            Descripcion = "Administrador del sistema",
                            Nombre_rol = "Admin"
                        },
                        new
                        {
                            Id_rol = 2,
                            Descripcion = "Supervisor de área",
                            Nombre_rol = "Supervisor"
                        },
                        new
                        {
                            Id_rol = 3,
                            Descripcion = "Técnico de dispositivos",
                            Nombre_rol = "Tecnico"
                        });
                });

            modelBuilder.Entity("AppDevicesMedical.Models.Status", b =>
                {
                    b.Property<int>("Id_status")
                        .HasColumnType("int");

                    b.Property<string>("Nombre_status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id_status");

                    b.ToTable("Status");
                });

            modelBuilder.Entity("AppDevicesMedical.Models.TipoDispositivo", b =>
                {
                    b.Property<int>("Id_tipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_tipo"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre_tipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id_tipo");

                    b.ToTable("TipoDispositivo");
                });

            modelBuilder.Entity("AppDevicesMedical.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("ApellidoMaterno")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("apellido_materno");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("apellido_paterno");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_creacion");

                    b.Property<int>("IdEspecialidad")
                        .HasColumnType("int")
                        .HasColumnName("id_especialidad");

                    b.Property<int>("IdRol")
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    b.Property<int>("IdStatus")
                        .HasColumnType("int")
                        .HasColumnName("id_status");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombres");

                    b.Property<string>("NumeroEmpleado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("numero_empleado");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("password_hash");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdEspecialidad");

                    b.HasIndex("IdRol");

                    b.HasIndex("IdStatus");

                    b.HasIndex("NumeroEmpleado")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("AppDevicesMedical.Models.Dispositivo", b =>
                {
                    b.HasOne("AppDevicesMedical.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("Id_categoria");

                    b.HasOne("AppDevicesMedical.Models.ClaseRiesgo", "ClaseRiesgo")
                        .WithMany("Dispositivos")
                        .HasForeignKey("Id_clase_riesgo");

                    b.HasOne("AppDevicesMedical.Models.Cuarto", "CuartoRequerido")
                        .WithMany()
                        .HasForeignKey("Id_cuarto_requerido");

                    b.HasOne("AppDevicesMedical.Models.TipoDispositivo", "TipoDispositivo")
                        .WithMany("Dispositivos")
                        .HasForeignKey("Id_tipo_dispositivo");

                    b.Navigation("Categoria");

                    b.Navigation("ClaseRiesgo");

                    b.Navigation("CuartoRequerido");

                    b.Navigation("TipoDispositivo");
                });

            modelBuilder.Entity("AppDevicesMedical.Models.Usuario", b =>
                {
                    b.HasOne("AppDevicesMedical.Models.Especialidad", "Especialidad")
                        .WithMany()
                        .HasForeignKey("IdEspecialidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppDevicesMedical.Models.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppDevicesMedical.Models.Status", "StatusUsuario")
                        .WithMany()
                        .HasForeignKey("IdStatus")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especialidad");

                    b.Navigation("Rol");

                    b.Navigation("StatusUsuario");
                });

            modelBuilder.Entity("AppDevicesMedical.Models.ClaseRiesgo", b =>
                {
                    b.Navigation("Dispositivos");
                });

            modelBuilder.Entity("AppDevicesMedical.Models.TipoDispositivo", b =>
                {
                    b.Navigation("Dispositivos");
                });
#pragma warning restore 612, 618
        }
    }
}
